name: Docker Deploy
on:
  workflow_dispatch:
  release:
    types: [ published ]
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet publish -c Release --no-restore
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: src/StatusWatchdog
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: trinitrotoluene/statuswatchdog/statuswatchdog
          tag_with_ref: true

